source_root: #full path to folder to contain Git repository working directories
docs_root: #full path to folder to contain built websites
websites:
  - id: "www.example.com"
    processor_root: #folder within Git repo which website processor (e.g. Hugo) should consider root directory
    content_processor: #e.g. 'hugo' or '' for default processor (which simply copies sources to output folder verbatim)
    index: # true or false - will the static website use pagefind indexing for search?
    github_webhook_secret_env_key: #name of an ENV variable containing a secret to be used by Github webhook
    git:
      clone_id: #e.g. "git@github.com:<GITHUB_ID>/<REPOSITORY_NAME>"
      branch: #e.g. "main"